export const COMPETITION_TYPES = [
  { value: 'triathlon', label: 'Triathlon' },
  { value: 'running', label: 'Course à pied' },
] as const

export const TRIATHLON_SUBTYPES = [
  { value: 'sprint', label: 'Sprint' },
  { value: 'olympic', label: 'Olympique' },
  { value: 'half-ironman', label: 'Half-Ironman' },
  { value: 'ironman', label: 'Ironman' },
] as const

export const RUNNING_SUBTYPES = [
  { value: '5k', label: '5K' },
  { value: '10k', label: '10K' },
  { value: 'semi-marathon', label: 'Semi-Marathon' },
  { value: 'marathon', label: 'Marathon' },
  { value: 'trail', label: 'Trail' },
  { value: 'ultra', label: 'Ultra' },
] as const

export const PRIORITIES = [
  { value: 'A', label: 'A - Objectif', color: 'bg-red-100 text-red-800 dark:bg-red-900/50 dark:text-red-300' },
  { value: 'B', label: 'B - Préparation', color: 'bg-amber-100 text-amber-800 dark:bg-amber-900/50 dark:text-amber-300' },
  { value: 'C', label: 'C - Plaisir', color: 'bg-green-100 text-green-800 dark:bg-green-900/50 dark:text-green-300' },
] as const

export const STATUSES = [
  { value: 'planned', label: 'Planifiée' },
  { value: 'registered', label: 'Inscrit' },
  { value: 'completed', label: 'Terminée' },
  { value: 'dns', label: 'DNS' },
  { value: 'dnf', label: 'DNF' },
] as const

// Sport colors - consistent palette across the app (aligned with Claude Design)
export const SPORT_COLORS = {
  swim: {
    name: 'Natation',
    color: '#0891B2',     // cyan-600 (Claude Design)
    colorDark: '#22d3ee', // cyan-400
    tint: 'rgba(8,145,178,.12)',
    bg: 'bg-cyan-600',
    bgLight: 'bg-cyan-50 dark:bg-cyan-900/20',
    text: 'text-cyan-600 dark:text-cyan-400',
    border: 'border-cyan-600',
    icon: '🏊',
  },
  bike: {
    name: 'Vélo',
    color: '#059669',     // emerald-600 (Claude Design)
    colorDark: '#34d399', // emerald-400
    tint: 'rgba(5,150,105,.12)',
    bg: 'bg-emerald-600',
    bgLight: 'bg-emerald-50 dark:bg-emerald-900/20',
    text: 'text-emerald-600 dark:text-emerald-400',
    border: 'border-emerald-600',
    icon: '🚴',
  },
  run: {
    name: 'Course',
    color: '#EA580C',     // orange-600 (Claude Design)
    colorDark: '#fb923c', // orange-400
    tint: 'rgba(234,88,12,.12)',
    bg: 'bg-orange-600',
    bgLight: 'bg-orange-50 dark:bg-orange-900/20',
    text: 'text-orange-600 dark:text-orange-400',
    border: 'border-orange-600',
    icon: '🏃',
  },
  strength: {
    name: 'Renforcement',
    color: '#a855f7', // purple-500
    colorDark: '#c084fc',
    tint: 'rgba(168,85,247,.12)',
    bg: 'bg-purple-500',
    bgLight: 'bg-purple-50 dark:bg-purple-900/20',
    text: 'text-purple-600 dark:text-purple-400',
    border: 'border-purple-500',
    icon: '💪',
  },
  rest: {
    name: 'Repos',
    color: '#94a3b8',
    colorDark: '#94a3b8',
    tint: 'rgba(100,116,139,.10)',
    bg: 'bg-slate-400',
    bgLight: 'bg-slate-100 dark:bg-slate-800',
    text: 'text-slate-500 dark:text-slate-400',
    border: 'border-slate-400',
    icon: '😴',
  },
  brick: {
    name: 'Enchaînement',
    color: '#ea580c',
    colorDark: '#fb923c',
    tint: 'rgba(234,88,12,.12)',
    bg: 'bg-orange-600',
    bgLight: 'bg-orange-50 dark:bg-orange-900/20',
    text: 'text-orange-700 dark:text-orange-400',
    border: 'border-orange-600',
    icon: '🔥',
  },
} as const

export type SportType = keyof typeof SPORT_COLORS

export const SESSION_TYPES = [
  { value: 'swim', label: 'Natation', color: SPORT_COLORS.swim.color, icon: SPORT_COLORS.swim.icon },
  { value: 'bike', label: 'Vélo', color: SPORT_COLORS.bike.color, icon: SPORT_COLORS.bike.icon },
  { value: 'run', label: 'Course', color: SPORT_COLORS.run.color, icon: SPORT_COLORS.run.icon },
  { value: 'strength', label: 'Renforcement', color: SPORT_COLORS.strength.color, icon: SPORT_COLORS.strength.icon },
  { value: 'rest', label: 'Repos', color: SPORT_COLORS.rest.color, icon: SPORT_COLORS.rest.icon },
  { value: 'brick', label: 'Enchaînement', color: SPORT_COLORS.brick.color, icon: SPORT_COLORS.brick.icon },
] as const

export const KNOWN_EVENTS = [
  'Marathon de Paris',
  'Semi de Paris',
  'Ironman Nice',
  'Ironman 70.3 Aix-en-Provence',
  'Triathlon de Paris',
  'Marathon du Mont-Blanc',
  'Trail du Ventoux',
  'Ekiden de Paris',
  'Marseille-Cassis',
  'SaintéLyon',
  'UTMB',
  'Trail des Templiers',
  'Marathon de Bordeaux',
  'Marathon de Lyon',
  'Marathon de Toulouse',
  'Triathlon de Deauville',
  'Triathlon de Nice',
  'Triathlon de La Baule',
  'Ironman Vichy',
  'Half Ironman Aix-en-Provence',
  'Marathon du Médoc',
  'Trail de la Sainte-Victoire',
  'Spartan Race Paris',
  'Les Templiers',
  'La Diagonale des Fous',
] as const

export const KNOWN_CITIES = [
  // Grandes villes
  'Paris',
  'Lyon',
  'Marseille',
  'Nice',
  'Bordeaux',
  'Toulouse',
  'Nantes',
  'Strasbourg',
  'Montpellier',
  'Lille',
  'Rennes',
  'Grenoble',
  'Rouen',
  'Toulon',
  'Dijon',
  'Reims',
  'Le Havre',
  'Saint-Étienne',
  'Clermont-Ferrand',
  'Tours',
  'Limoges',
  'Amiens',
  'Perpignan',
  'Besançon',
  'Orléans',
  'Metz',
  'Mulhouse',
  'Caen',
  'Nancy',
  'Avignon',
  // Villes de compétitions populaires
  'Annecy',
  'Aix-en-Provence',
  'Chamonix',
  'Vichy',
  'Gérardmer',
  'Deauville',
  'La Baule',
  'Embrun',
  'Millau',
  'Saint-Malo',
  'Biarritz',
  'La Rochelle',
  'Cannes',
  'Antibes',
  'La Ciotat',
  'Cassis',
  'Hyères',
  'Fréjus',
  'Saint-Tropez',
  'Le Grau-du-Roi',
  'Gruissan',
  'Sète',
  'Cap d\'Agde',
  'Argelès-sur-Mer',
  'Collioure',
  'Arcachon',
  'Lacanau',
  'Hossegor',
  'Hendaye',
  'Saint-Jean-de-Luz',
  'Bayonne',
  'Pau',
  'Lourdes',
  'Font-Romeu',
  'Les Deux Alpes',
  'L\'Alpe d\'Huez',
  'Méribel',
  'Courchevel',
  'Tignes',
  'Val d\'Isère',
  'Morzine',
  'Les Gets',
  'Megève',
  'La Clusaz',
  'Le Grand-Bornand',
  'Albertville',
  'Chambéry',
  'Aix-les-Bains',
  'Évian-les-Bains',
  'Thonon-les-Bains',
  'Colmar',
  'Obernai',
  'Saverne',
  'Haguenau',
  'Sélestat',
  'Épinal',
  'Vittel',
  'Contrexéville',
  'Bar-le-Duc',
  'Verdun',
  'Troyes',
  'Châlons-en-Champagne',
  'Épernay',
  'Charleville-Mézières',
  'Compiègne',
  'Senlis',
  'Chantilly',
  'Fontainebleau',
  'Versailles',
  'Saint-Germain-en-Laye',
  'Saint-Cloud',
  'Boulogne-Billancourt',
  'Vincennes',
  'Saint-Denis',
  'Montreuil',
  'Vannes',
  'Lorient',
  'Quimper',
  'Brest',
  'Saint-Brieuc',
  'Dinard',
  'Dinan',
  'Carnac',
  'Concarneau',
  'Quiberon',
  'Belle-Île-en-Mer',
  'Île de Ré',
  'Île d\'Oléron',
  'Noirmoutier',
  'Les Sables-d\'Olonne',
  'Pornic',
  'Saint-Nazaire',
  'La Roche-sur-Yon',
  'Niort',
  'Poitiers',
  'Angoulême',
  'Cognac',
  'Royan',
  'Saintes',
  'Rochefort',
  'Périgueux',
  'Bergerac',
  'Sarlat',
  'Brive-la-Gaillarde',
  'Tulle',
  'Aurillac',
  'Le Puy-en-Velay',
  'Saint-Flour',
  'Mende',
  'Rodez',
  'Albi',
  'Castres',
  'Carcassonne',
  'Narbonne',
  'Béziers',
  'Agde',
  'Nîmes',
  'Uzès',
  'Arles',
  'Les Saintes-Maries-de-la-Mer',
  'Martigues',
  'Salon-de-Provence',
  'Apt',
  'Orange',
  'Carpentras',
  'Vaison-la-Romaine',
  'Sisteron',
  'Gap',
  'Briançon',
  'Barcelonnette',
  'Digne-les-Bains',
  'Manosque',
  'Forcalquier',
  'Apt',
  'Cavaillon',
  'Isle-sur-la-Sorgue',
  'Gordes',
  'Roussillon',
  'Bonnieux',
  'Lourmarin',
  'Menton',
  'Monaco',
  'Èze',
  'Villefranche-sur-Mer',
  'Beaulieu-sur-Mer',
  'Saint-Jean-Cap-Ferrat',
  'Cagnes-sur-Mer',
  'Vence',
  'Saint-Paul-de-Vence',
  'Grasse',
  'Mougins',
  'Vallauris',
  'Juan-les-Pins',
  'Mandelieu-la-Napoule',
  'Théoule-sur-Mer',
  'Saint-Raphaël',
  'Sainte-Maxime',
  'Le Lavandou',
  'Bormes-les-Mimosas',
  'Le Pradet',
  'Sanary-sur-Mer',
  'Bandol',
  'Six-Fours-les-Plages',
  'La Seyne-sur-Mer',
] as const

export const LEVELS = [
  { value: 'beginner', label: 'Debutant', description: 'Peu ou pas d\'experience dans ce sport' },
  { value: 'intermediate', label: 'Intermediaire', description: '1-3 ans de pratique reguliere' },
  { value: 'advanced', label: 'Avance', description: '3+ ans, competitions regulieres' },
] as const

export const INTENSITIES = [
  { value: 'easy', label: 'Facile', color: 'bg-green-100 text-green-800 dark:bg-green-900/50 dark:text-green-300' },
  { value: 'moderate', label: 'Modéré', color: 'bg-blue-100 text-blue-800 dark:bg-blue-900/50 dark:text-blue-300' },
  { value: 'hard', label: 'Intense', color: 'bg-orange-100 text-orange-800 dark:bg-orange-900/50 dark:text-orange-300' },
  { value: 'interval', label: 'Intervalles', color: 'bg-red-100 text-red-800 dark:bg-red-900/50 dark:text-red-300' },
  { value: 'race-pace', label: 'Allure course', color: 'bg-purple-100 text-purple-800 dark:bg-purple-900/50 dark:text-purple-300' },
] as const

// Helper function to get sport color config
export function getSportColor(sport: string) {
  return SPORT_COLORS[sport as SportType] || SPORT_COLORS.rest
}
